title: Hannah Gordon
logo: "/images/Senior picture.jpg"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/hannahm-gordon">LinkedIn</a> 
  <br>
  <a href="pdf/Current Resume Hannah Gordon (1).pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://www.GitHub.com/donbowen/">GitHub</a>  

  
theme: jekyll-theme-minimal
