title: Hannah Gordon
logo: "/images/Senior picture.jpg"  # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/hannahm-gordon" target="_blank" rel="noopener noreferrer">LinkedIn</a> 
  <br>
  <a href="pdf/Current Resume Hannah Gordon (1).pdf" class="btn btn--info" target="_blank" rel="noopener noreferrer">Resume</a>  
  <br>
  <a href="https://github.com/hannahmgordon" target="_blank" rel="noopener noreferrer">GitHub</a>  

theme: jekyll-theme-minimal
 
